INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Avon and Somerset', 14625, 905700);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Bedfordshire', 5780, 595800);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cambridgeshire', 7378, 760700);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cheshire', 8882, 1003600);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('City of London', 570, 8000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cleveland', 8610, 867600);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cumbria', 3563, 498800);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Derbyshire', 11804, 996000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Devon and Cornwall', 11977, 1663600);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dorset', 6571, 708100);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Durham', 6956, 880200);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dyfed Powys', 4012, 500000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Essex', 18206, 1688400);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gloucestershire', 5667, 839000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gwent', 5207, 560500);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hampshire', 17619, 1705700);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hertfordshire', 9139, 1066100);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Humberside', 8966, 914000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Kent', 17506, 1647100);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lancashire', 19394, 1451500);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Leicestershire', 9299, 933400);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lincolnshire', 6398, 1010600);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Merseyside', 16378, 1350200);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Metropolitan', 95527, 8174000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Norfolk', 7459, 840600);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Wales', 6886, 698400);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Yorkshire ', 4803, 1067000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northamptonshire', 4989, 678200);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northumberland', 7327, 310600);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Nottinghamshire', 7823, 823100);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Wales', 11277, 1340000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Yorkshire ', 11565, 1299400);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Staffordshire', 8218, 1064800);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Suffolk', 3989, 709300);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Surrey', 5841, 1098300);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Sussex', 9939, 1531200);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Thames Valley', 14276, 2420000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Warwickshire', 3180, 526800);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Mercia', 6369, 1190000);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Yorkshire ', 22217, 2181200);
INSERT INTO `statistics_june` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Wiltshire', 3224, 642000);
