INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Avon and Somerset', 7241, 905700);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Bedfordshire', 3991, 595800);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cambridgeshire', 6126, 760700);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cheshire', 8482, 1003600);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('City of London', 370, 8000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cleveland', 6542, 867600);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cumbria', 3249, 498800);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Derbyshire', 7494, 996000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Devon and Cornwall', 5320, 1663600);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dorset', 6165, 708100);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Durham', 5216, 880200);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dyfed Powys', 1723, 500000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Essex', 14429, 1688400);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gloucestershire', 3583, 839000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gwent', 2761, 560500);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hampshire', 9734, 1705700);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hertfordshire', 5240, 1066100);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Humberside', 8414, 914000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Kent', 15889, 1647100);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lancashire', 5614, 1451500);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Leicestershire', 7711, 933400);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lincolnshire', 5978, 1010600);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Merseyside', 14539, 1350200);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Metropolitan', 94605, 8174000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Norfolk', 5840, 840600);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Wales', 1644, 698400);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Yorkshire ', 5425, 1067000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northamptonshire', 5145, 678200);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northumberland', 6614, 310600);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Nottinghamshire', 7769, 823100);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Wales', 15846, 1340000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Yorkshire ', 12519, 1299400);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Staffordshire', 5112, 1064800);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Suffolk', 4454, 709300);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Surrey', 6280, 1098300);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Sussex', 9643, 1531200);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Thames Valley', 14589, 2420000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Warwickshire', 3170, 526800);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Mercia', 6963, 1190000);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Yorkshire ', 24240, 2181200);
INSERT INTO `statistics_july` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Wiltshire', 2699, 642000);
