INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Avon and Somerset', 7312, 905700);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Bedfordshire', 3942, 595800);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cambridgeshire', 5744, 760700);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cheshire', 6400, 1003600);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('City of London', 272, 8000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cleveland', 6049, 867600);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cumbria', 2975, 498800);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Derbyshire', 7132, 996000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Devon and Cornwall', 4865, 1663600);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dorset', 5907, 708100);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Durham', 4888, 880200);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dyfed Powys', 1585, 500000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Essex', 13799, 1688400);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gloucestershire', 3198, 839000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gwent', 2524, 560500);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hampshire', 10264, 1705700);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hertfordshire', 7432, 1066100);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Humberside', 8143, 914000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Kent', 15864, 1647100);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lancashire', 5374, 1451500);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Leicestershire', 7648, 933400);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lincolnshire', 5651, 1010600);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Merseyside', 13687, 1350200);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Metropolitan', 89240, 8174000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Norfolk', 5702, 840600);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Wales', 1717, 698400);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Yorkshire ', 4710, 1067000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northamptonshire', 4802, 678200);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northumberland', 7071, 310600);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Nottinghamshire', 7662, 823100);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Wales', 12361, 1340000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Yorkshire ', 11988, 1299400);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Staffordshire', 4813, 1064800);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Suffolk', 4181, 709300);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Surrey', 5418, 1098300);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Sussex', 8215, 1531200);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Thames Valley', 14261, 2420000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Warwickshire', 3226, 526800);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Mercia', 6615, 1190000);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Yorkshire ', 24218, 2181200);
INSERT INTO `statistics_august` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Wiltshire', 2512, 642000);
