INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Avon and Somerset', 14046, 905700);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Bedfordshire', 4026, 595800);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cambridgeshire', 5756, 760700);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cheshire', 5363, 1003600);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('City of London', 270, 8000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cleveland', 5908, 867600);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cumbria', 3032, 498800);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Derbyshire', 7001, 996000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Devon and Cornwall', 4914, 1663600);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dorset', 6310, 708100);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Durham', 4902, 880200);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dyfed Powys', 1555, 500000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Essex', 18207, 1688400);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gloucestershire', 3533, 839000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gwent', 2489, 560500);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hampshire', 9795, 1705700);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hertfordshire', 6307, 1066100);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Humberside', 8106, 914000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Kent', 14752, 1647100);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lancashire', 5659, 1451500);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Leicestershire', 8362, 933400);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lincolnshire', 6000, 1010600);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Merseyside', 12953, 1350200);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Metropolitan', 92225, 8174000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Norfolk', 5843, 840600);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Wales', 3098, 698400);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Yorkshire ', 6570, 1067000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northamptonshire', 4735, 678200);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northumberland', 7277, 310600);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Nottinghamshire', 7626, 823100);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Wales', 7961, 1340000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Yorkshire ', 11564, 1299400);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Staffordshire', 4319, 1064800);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Suffolk', 4188, 709300);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Surrey', 5476, 1098300);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Sussex', 6964, 1531200);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Thames Valley', 13706, 2420000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Warwickshire', 3055, 526800);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Mercia', 6604, 1190000);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Yorkshire ', 22024, 2181200);
INSERT INTO `statistics_may` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Wiltshire', 2775, 642000);
