INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Avon and Somerset', 13095, 905700);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Bedfordshire', 5046, 595800);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cambridgeshire', 6482, 760700);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cheshire', 9503, 1003600);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('City of London', 358, 8000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cleveland', 7741, 867600);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Cumbria', 3823, 498800);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Derbyshire', 10528, 996000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Devon and Cornwall', 11231, 1663600);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dorset', 6175, 708100);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Durham', 6784, 880200);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Dyfed Powys', 3629, 500000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Essex', 17166, 1688400);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gloucestershire', 5712, 839000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Gwent', 5407, 560500);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hampshire', 16123, 1705700);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Hertfordshire', 8422, 1066100);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Humberside', 8189, 914000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Kent', 18183, 1647100);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lancashire', 19716, 1451500);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Leicestershire', 8271, 933400);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Lincolnshire', 6072, 1010600);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Merseyside', 14994, 1350200);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Metropolitan', 87199, 8174000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Norfolk', 6367, 840600);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Wales', 6229, 698400);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('North Yorkshire ', 6188, 1067000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northamptonshire', 6349, 678200);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Northumberland', 17241, 310600);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Nottinghamshire', 11247, 823100);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Wales', 12340, 1340000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('South Yorkshire ', 11471, 1299400);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Staffordshire', 8151, 1064800);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Suffolk', 4825, 709300);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Surrey', 8022, 1098300);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Sussex', 13590, 1531200);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Thames Valley', 17119, 2420000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Warwickshire', 4332, 526800);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Mercia', 6828, 1190000);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('West Yorkshire ', 26564, 2181200);
INSERT INTO `statistics_april` (`city`, `Number_of_crimes`, `total_population`) VALUES ('Wiltshire', 4514, 642000);
